# Generated by Django 5.1.6 on 2025-04-08 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poplatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popis', models.CharField(blank=True, max_length=255)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypUctu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, unique=True)),
                ('popis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ucet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_uctu', models.CharField(max_length=20, unique=True)),
                ('datum_zalozeni', models.DateTimeField(auto_now_add=True)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ucty', to='banka.typuctu')),
            ],
        ),
        migrations.CreateModel(
            name='UrokovaSazba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sazba', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platna_od', models.DateField()),
                ('platna_do', models.DateField(blank=True, null=True)),
                ('typ_uctu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urokove_sazby', to='banka.typuctu')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('datum_registrace', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='poplatky',
        ),
        migrations.DeleteModel(
            name='uroksazby',
        ),
        migrations.DeleteModel(
            name='zakaznici',
        ),
        migrations.AddField(
            model_name='poplatek',
            name='ucet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poplatky', to='banka.ucet'),
        ),
        migrations.AddField(
            model_name='ucet',
            name='zakaznik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucty', to='banka.zakaznik'),
        ),
    ]
